### ISSUE TITLE
Some questions about THUMOS test features

### ISSUE THREAD

**Issue by liming-ai** [bfshi/DGAM-Weakly-Supervised-Action-Localization#15]
hi @bfshi , thanks for your amazing work and congratulates you received many PhD offers.

I noticed that there are some code (e.g. [UM](https://github.com/Pilhyeon/WTAL-Uncertainty-Modeling), [STPN](https://github.com/bellos1203/STPN)) dropped some test videos due to their false annotation.

I noticed that the provided dataset by you has a txt file named `THUMOS14_test_vid_list.txt`, I want to know whether the order of feature naming is consistent with the order in this file?

e.g. 

video_test_0000004 (the first row in `THUMOS14_test_vid_list.txt`) -> 1.npy
video_test_0001558 (the last row in `THUMOS14_test_vid_list.txt`) -> 210.npy

Thanks again and congratulates again, hope you can reply to me!

**Comment by liming-ai** [comment]
I found that the dataset provided by this repo has removed some falsely annotated videos(i.e. 270, 1496 in test dataset), like UM, STPN did.

**Comment by zfhxi** [comment]
I also noted this difference, I wonder if it is unfair to compare the experiment results with other methods which don't remove videos.
