### ISSUE TITLE
Are the provided features normalised?

### ISSUE THREAD

**Issue by dmoltisanti** [bfshi/DGAM-Weakly-Supervised-Action-Localization#5]
Hi, thank you very much for sharing your code with us! Quick question about the provided I3D features. 

Are they normalised in any way?

Also, if I want to use DGAM with my own features, should I normalise them? I know DGAM uses (amongst others) a reconstruction loss so this might be an important detail.

Thanks in advance!

**Comment by bfshi** [comment]
Hi Davide, thanks for your interest!

I think the feature isn't normalized beforehand (to verify this, I output the feture mean and variance in each batch, and I didn't observe a 0-mean or unit var). 

If you are using your own feature, I think it may help the steadiness of training if you normalize the feature first. But I'm not sure if it will help the final performance.

**Comment by dmoltisanti** [comment]
I see, thank you for your clear and prompt response :) closing the issue now!
